검색 페이지 API 수정
ootd-zip/client pull request #266
Opened 2024-04-08 13:16 UTC by JungYeonHwi

# 🔢 이슈 번호

- close #259

## ⚙ 작업 사항

- [ ] OOTDtotalCount 작업
- [ ] imageCount 추가
- [ ] searchType 추가

## 📃 참고자료

-

## 📷 스크린샷
![image](https://github.com/ootd-zip/client/assets/64068511/c782d546-97d7-4900-bd81-d440163b8ba3)

2024-04-08 13:51 UTC, skrgus6269 approved these changes
고생하셨습니다:)

2024-04-08 14:26 UTC, skrgus6269 requested changes
혹시 
1. 유저 프로필 클릭 시 마이페이지로 이동
2. 팔로우 기능 
까지 작업 해주실 수 있을까요?

2024-04-08 17:00 UTC, JungYeonHwi commented
1번) 처리 완료
2번) 낙현 이슈(팔로잉 팔로우 API)에서 처리~^.^

2024-04-09 01:04 UTC, skrgus6269 approved these changes
고생하셨습니다 :)

2024-04-09 04:32 UTC, merged